services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${WP_PORT}:80"
    environment:
      DB_HOST: db:3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads
    labels:
      - traefik.enable=true
      - traefik.http.routers.app_http.entryPoints=http
      - traefik.http.routers.app_http.middlewares=redirect-to-https
      - traefik.http.routers.app_http.rule=HostRegexp(`^.+\.vavinde\.ro$`) || Host(`vavinde.ro`)
      - traefik.http.routers.app_https.entryPoints=https
      - traefik.http.routers.app_https.rule=HostRegexp(`^.+\.vavinde\.ro$`) || Host(`vavinde.ro`)
      - traefik.http.routers.app_https.service=app_service
      - traefik.http.routers.app_https.tls.certresolver=letsencrypt
      - traefik.http.routers.app_https.tls=true
      - traefik.http.services.app_service.loadbalancer.server.port=80

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

  wpcli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    restart: "no"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads
    environment:
      DB_HOST: db:3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  db_data:
  wp_uploads:
